/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180595841/work/aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-02-10 22:16:25,708   INFO  **********************Start training kitti_models/second(default)**********************
epochs:   0%|                                                                                                                                                                                      | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                                                               | 0/586 [00:00<?, ?it/s]
  File "train.py", line 238, in <module>
    main()
  File "train.py", line 191, in main
    train_model(
  File "/home/stephen/Documents/3DDet/tools/train_utils/train_utils.py", line 116, in train_model
    accumulated_iter = train_one_epoch(
  File "/home/stephen/Documents/3DDet/tools/train_utils/train_utils.py", line 50, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/home/stephen/Documents/3DDet/tools/../pcdet/models/__init__.py", line 42, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/home/stephen/anaconda3/envs/kitti/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/stephen/Documents/3DDet/tools/../pcdet/models/detectors/second_net.py", line 10, in forward
    pdb.set_trace()
NameError: name 'pdb' is not defined