2022-02-08 13:24:09,601 INFO    MainThread:291110 [wandb_setup.py:_flush():71] setting env: {}
2022-02-08 13:24:09,601 INFO    MainThread:291110 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-08 13:24:09,601 INFO    MainThread:291110 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_132409-kw3xowar/logs/debug.log
2022-02-08 13:24:09,602 INFO    MainThread:291110 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_132409-kw3xowar/logs/debug-internal.log
2022-02-08 13:24:09,602 INFO    MainThread:291110 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f48a2688130>
2022-02-08 13:24:09,602 INFO    MainThread:291110 [wandb_init.py:init():404] calling init triggers
2022-02-08 13:24:09,602 INFO    MainThread:291110 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-08 13:24:09,602 INFO    MainThread:291110 [wandb_init.py:init():460] starting backend
2022-02-08 13:24:09,602 INFO    MainThread:291110 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-08 13:24:09,605 INFO    MainThread:291110 [backend.py:ensure_launched():216] starting backend process...
2022-02-08 13:24:09,625 INFO    MainThread:291110 [backend.py:ensure_launched():221] started backend process with pid: 291839
2022-02-08 13:24:09,626 INFO    MainThread:291110 [wandb_init.py:init():469] backend started and connected
2022-02-08 13:24:09,644 INFO    MainThread:291110 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-08 13:24:09,644 INFO    MainThread:291110 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-08 13:24:09,644 INFO    MainThread:291110 [wandb_init.py:init():533] updated telemetry
2022-02-08 13:24:09,675 INFO    MainThread:291110 [wandb_init.py:init():563] communicating current version
2022-02-08 13:24:10,266 INFO    MainThread:291110 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-08 13:24:10,268 INFO    MainThread:291110 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-08 13:24:10,543 INFO    MainThread:291110 [wandb_init.py:init():606] starting run threads in backend
2022-02-08 13:24:12,637 INFO    MainThread:291110 [wandb_run.py:_console_start():1810] atexit reg
2022-02-08 13:24:12,637 INFO    MainThread:291110 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-08 13:24:12,637 INFO    MainThread:291110 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-08 13:24:12,639 INFO    MainThread:291110 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-08 13:24:12,639 INFO    MainThread:291110 [wandb_init.py:init():633] run started, returning control to user process
2022-02-08 13:24:12,639 INFO    MainThread:291110 [wandb_run.py:_config_callback():956] config_cb None None {}
2022-02-08 13:24:12,640 INFO    MainThread:291110 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:24:12,640 INFO    MainThread:291110 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:24:12,795 INFO    MainThread:291110 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:24:12,802 INFO    MainThread:291110 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:24:12,802 INFO    MainThread:291110 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:24:12,854 INFO    MainThread:291110 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:24:12,855 INFO    MainThread:291110 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:24:12,855 INFO    MainThread:291110 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:24:12,913 INFO    MainThread:291110 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:24:12,916 INFO    MainThread:291110 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:24:12,916 INFO    MainThread:291110 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:24:14,777 INFO    MainThread:291110 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:24:14,782 INFO    MainThread:291110 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:24:14,782 INFO    MainThread:291110 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:24:15,754 INFO    MainThread:291110 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:24:15,755 INFO    MainThread:291110 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:24:15,756 INFO    MainThread:291110 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:24:16,351 INFO    MainThread:291110 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:24:16,383 INFO    MainThread:291110 [wandb_init.py:_pause_backend():284] pausing backend
2022-02-08 13:24:16,383 INFO    MainThread:291110 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:26:11,138 INFO    MainThread:291110 [wandb_init.py:_resume_backend():293] resuming backend
2022-02-08 13:26:11,154 INFO    MainThread:291110 [wandb_setup.py:_flush():71] setting env: {}
2022-02-08 13:26:11,154 INFO    MainThread:291110 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-08 13:26:11,154 INFO    MainThread:291110 [wandb_init.py:_log_setup():371] Logging user logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_132611-2dw9v1cz/logs/debug.log
2022-02-08 13:26:11,154 INFO    MainThread:291110 [wandb_init.py:_log_setup():372] Logging internal logs to /home/stephen/Documents/3DDet/tools/wandb/run-20220208_132611-2dw9v1cz/logs/debug-internal.log
2022-02-08 13:26:11,154 INFO    MainThread:291110 [wandb_init.py:init():404] calling init triggers
2022-02-08 13:26:11,154 INFO    MainThread:291110 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-02-08 13:26:11,154 INFO    MainThread:291110 [wandb_init.py:init():424] re-initializing run, found existing run on stack: kw3xowar
2022-02-08 13:26:11,156 INFO    MainThread:291110 [wandb_run.py:finish():1457] finishing run nelsonsw5/objdet_GT_Viz/kw3xowar
2022-02-08 13:26:11,156 INFO    MainThread:291110 [jupyter.py:save_history():429] not saving jupyter history
2022-02-08 13:26:11,157 INFO    MainThread:291110 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-08 13:26:11,157 INFO    MainThread:291110 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-08 13:26:11,157 INFO    MainThread:291110 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-08 13:26:11,159 INFO    MainThread:291110 [wandb_run.py:_restore():1752] restore
2022-02-08 13:26:11,274 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 13:26:11,555 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 1074
}

2022-02-08 13:26:11,657 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11713
}

2022-02-08 13:26:11,761 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11713
}

2022-02-08 13:26:11,863 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1074
  total_bytes: 11713
}

2022-02-08 13:26:11,966 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11713
  total_bytes: 11713
}

2022-02-08 13:26:12,070 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11713
  total_bytes: 11713
}

2022-02-08 13:26:12,172 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11713
  total_bytes: 11713
}

2022-02-08 13:26:12,274 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11713
  total_bytes: 11713
}

2022-02-08 13:26:12,625 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11713
  total_bytes: 11713
}

2022-02-08 13:26:13,053 INFO    MainThread:291110 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 11713
  total_bytes: 11713
}
local_info {
}

2022-02-08 13:26:14,217 INFO    MainThread:291110 [wandb_run.py:_append_files():2180] logging synced files
